import {gql} from 'apollo-boost';

// Posts and coments domain

const getPosts = gql`
    {
        posts{
            id
            title
            summaryData{
                summary
            }
            author {
                username
                avatarUrl
                points
            }
            createdAt
            pointsData {
                likes
                dislikes
            }
            authorPoints
        }
    }
`;

const getFullPost = gql`
    query($postId: ID!){
        post(postId: $postId){
            id
            title
            body
            tags
            views
            author{id username avatarUrl email points}
            summaryData{autogenerated summary}
            pointsData{likes}
            comments{text author{username} likes}
            createdAt
            authorPoints    
        }  
    }
`;

const getTotalPosts = gql`
    {
    getTotalPosts
  }
`;

// User and authentication domain

const addUser = gql`
mutation($email: String!, $username: String!,$password: String!, $confirmpassword: String!){
        signin(email: $email, username: $username,
            password: $password, confirmpassword: $confirmpassword){
                id
                username
            }
        }
`;

const loginUser = gql`
    query($username: String!, $password: String!) {
        login(username: $username, password: $password){
        id
        username
        email
        avatarUrl
        }
    }
`;

const getUser = gql`
    query($userId: ID, $postId: ID){
        user(userId: $userId){
            id
            username
            email
            avatarUrl
            postsLoved(postIds: [$postId])
        }
    }
`;


// Others

const likePost = gql`
    mutation($postId: ID!, $userId: ID!) {
        likePost(
            postId: $postId, 
            userId: $userId
        )
    }
`;

const unlikePost = gql`
    mutation($postId: ID!, $userId: ID!) {
        unlikePost(
            postId: $postId, 
            userId: $userId
        )
    }
`;


export {getPosts, getTotalPosts, getFullPost, addUser, loginUser, getUser,likePost, unlikePost};